image: ruby:latest

stages:
  - test
  - publish

variables:
  SSH_AUTH_SOCK: "/ssh-agent"

before_script:
  - mkdir -p /root/.ssh && ssh-keyscan -H codevault.io > /root/.ssh/known_hosts 2>/dev/null
  - bundle config jobs 8
  - bundle install --path=/tmp/bundler --quiet

rubocop:
  stage: test
  script:
    - bundle exec rubocop

publish_gem:
  stage: publish
  script:
    - ./scripts/publish_gem.sh
  only:
    - master
  when: manual
