image: ruby:latest

variables:
  SSH_AUTH_SOCK: "/ssh-agent"

before_script:
  - mkdir -p /root/.ssh && ssh-keyscan -H codevault.io > /root/.ssh/known_hosts 2>/dev/null
  - bundle config jobs 8
  - bundle install --path=/tmp/bundler --quiet

rubocop:
  script:
    - bundle exec rubocop
